version: '3.2'

services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    container_name: frontend-side
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    stdin_open: true
    tty: true
    depends_on:
      - loadbalancer
    networks:
      - letsDo-network

  backend1:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    environment:
      - DB_USER
      - DB_PASSWORD
    networks:
      - letsDo-network

  backend2:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    environment:
      - DB_USER
      - DB_PASSWORD
    networks:
      - letsDo-network

  database:
    image: mongo
    container_name: mongo-db

  loadbalancer:
    build:
      context: loadbalancer
      dockerfile: Dockerfile
    links:
      - backend1
      - backend2
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - letsDo-network

networks:
  letsDo-network:
    driver: bridge
