version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    container_name: frontend-side
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - letsDo-network

  backend:
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - .env
    # container_name: node-server
    # ports:
    #   - '${BACKEND_PORT}:${BACKEND_PORT}'
    restart: always
    depends_on:
      - database
    environment:
      - DB_USER
      - DB_PASSWORD
    networks:
      - letsDo-network

  database:
    image: mongo
    container_name: mongo-db

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - letsDo-network

networks:
  letsDo-network:
    driver: bridge
